### ISSUE TITLE
How to generate outside or inside uvs data?

### ISSUE THREAD

**Issue by JoeyKo** [Deadolus/three.js-ring-editor#1]
Hi, this is a good demo, but i don't know how to get uvs data from 3d software(such as blender).

**Comment by Deadolus** [comment]
Hi @JoeyKo, thank you for your interest. 
This has nothing to do with blender. 
If you have questions on how to import stls in to blender, please ask at a blender forum.
Thank you very much.

**Comment by JoeyKo** [comment]
@Deadolus Thank you for you reply.
It's not a question about blender.
I'm just confused about the code `newRing.geometry.faceVertexUvs[1] ` or `newRing.geometry.faceVertexUvs[4]` that your wrote.
If I have a 3d model with front and back side, how can i generate different faceVertexUvs data?
